version: '3.8'

services:
  db:
    build: 
      context: ./mysql
      dockerfile: Dockerfile.prod
    container_name: db
    # command: --init-file /data/application/init.sql
    restart: always
    tty: true
    networks:
      - node-network
    volumes:
      - ./mysql/db-volume:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    container_name: nginx
    restart: always
    ports: 
      - 8080:80
    depends_on:
      - node
    networks:
      - node-network
  node:
    build:
      context: ./node
      dockerfile: Dockerfile.prod
    container_name: node
    restart: always
    depends_on:
      - db
    networks:
      - node-network

networks:
  node-network:
    driver: bridge